app:
  github-token: ${GITHUB_TOKEN} # env variable
  stackoverflow:
    key: ${SO_TOKEN_KEY}
    access-token: ${SO_ACCESS_TOKEN}
  bot-url: http://bot:8080
  github-api-url: https://api.github.com
  github-repo-issue-format: repos/%s/issues?per_page=1
  stack-exchange-api-url: https://api.stackexchange.com/2.2
  updates-path: /updates
  page-size: 50
  preview-size: 200
  access-type: jpa
  main-transport: http

  kafka:
    topic: update
    partitions: 3
    replication-factor: 1

  resilience:
    circuit-breaker-failure-rate-threshold: 100
    circuit-breaker-minimum-number-of-calls: 10
    circuit-breaker-permitted-calls-in-half-open-state: 2
    circuit-breaker-sliding-window-size: 5
    circuit-breaker-wait-duration-in-open-state: 1
    circuit-breaker-slow-call-duration-threshold: 5
    retry-max-attempts: 3
    retry-wait-duration: 100
    time-limiter-timeout-duration: 10

resilience4j:
  ratelimiter:
    instances:
      default:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: true

spring:
  kafka:
    producer:
      properties.spring:
          json.add.type.headers: false
      bootstrap-servers: localhost:19092, localhost:29092

  datasource:
    url: jdbc:postgresql://postgresql:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  application:
    name: Scrapper

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  structured:
    format:
      #console: ecs

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
