app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  scrapper-url: "http://localhost:8081"
  set-commands-url-format: "https://api.telegram.org/bot%s/setMyCommands"
  tg-chat-path: "/tg-chat"
  link-path: "/links?Tg-Chat-Id="
  cache-ttl: 5

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  structured:
    format:
      #console: ecs

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
