app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  scrapper-url: http://scrapper:8081
  set-commands-url-format: https://api.telegram.org/bot%s/setMyCommands
  tg-chat-path: /tg-chat/
  link-path: /links?Tg-Chat-Id=

  cache:
    cache-ttl: 5

  enable-kafka: false
  kafka:
    concurrency: 3
    group-id: group
    topic: updates
    retry:
      attempts: 1
      multiplier: 2
      delay: 5000

  resilience:
    circuit-breaker-failure-rate-threshold: 100
    circuit-breaker-minimum-number-of-calls: 10
    circuit-breaker-permitted-calls-in-half-open-state: 2
    circuit-breaker-sliding-window-size: 5
    circuit-breaker-wait-duration-in-open-state: 1
    circuit-breaker-slow-call-duration-threshold: 5
    retry-max-attempts: 3
    retry-wait-duration: 100
    time-limiter-timeout-duration: 10

resilience4j:
  ratelimiter:
    instances:
      default:
        limitForPeriod: 5
        limitRefreshPeriod: 1s
        timeoutDuration: 0
        registerHealthIndicator: true

spring:
  kafka:
    consumer.properties:
      enable.auto.commit: false
      auto.offset.reset: earliest
      fetch.min.bytes: 1024
      fetch.max.bytes: 1048576
      fetch.max.wait.ms: 10000
      max.poll.interval.ms: 10000
      max.poll.records: 10
      bootstrap-servers: localhost:19092, localhost:29092

      producer.properties:
        spring:
            json.add.type.headers: false
        bootstrap-servers: localhost:19092, localhost:29092

  application:
    name: Bot

  liquibase:
    enabled: false

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

logging:
  structured:
    format:
      #console: ecs

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
